spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        bootstrap: true
        git:
          uri: https://github.com/fabianogoes/config-server-store.git

server:
  port: 9092

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka