spring:
  application:
    name: discover-server

eureka:
  client:
#    serviceUrl:
#      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/
      register-with-eureka: false
      fetch-registry: false

server:
  port: 8761

